services:
  frontend:
    image: node:24-alpine
    container_name: create-step-tool-frontend
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend
    command: sh -c "npm install && npm run dev -- --host --port 8002"
    networks:
      - default
      - shared-gateway-net
    restart: unless-stopped

  backend:
    image: node:24-alpine
    container_name: create-step-tool-backend
    working_dir: /app/backend
    volumes:
      - ./backend:/app/backend
    environment:
      - PORT=8003
    command: sh -c "node server.js"
    networks:
      - default
      - shared-gateway-net
    restart: unless-stopped



networks:
  shared-gateway-net:
    external: true
